name: Effort distribution

on:
  push:
    branches:
      - main
      - 'ci/**'

jobs:
  generate-distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Compile report
        run: make git-fame

      - name: Export PDF
        uses: actions/upload-artifact@v4
        with:
          name: effort_distribution
          path: reports/effort_distribution.pdf
